apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-per-volume
  namespace: springboot
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage : 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-per-claim
  namespace: springboot
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi