apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-per-volume2
  namespace: springboot
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage : 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-per-claim2
  namespace: springboot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi