apiVersion: apps/v1
kind: Deployment
metadata: 
    name: java
    namespace: springboot
    labels:
      app: java
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
        containers:
          - name: java
            image: ma5k/devops-demo
            imagePullPolicy: Always
            ports: 
             - containerPort: 8080
            env:
              - name: SPRING_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef: 
                    name: sql-pass
                    key: sql-passing
              - name: SPRING_SECURITY_USER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: user-pass
                    key: user-passing
---
apiVersion: v1
kind: Service
metadata:
  name: java-servcie
  namespace: springboot
spec: 
  selector:
    app: java
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32520