apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: springboot
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
      type: Recreate
  template:
      metadata:
        labels:
          app: mysql
      spec:
        containers:
          - image: mysql:8.0.31
            name: mysql
            env:
              - name: MYSQL_DATABASE
                value: "customerapi"
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef: 
                    name: sql-pass
                    key: sql-passing
            ports:
              - containerPort: 3306
                name: mysql
            volumeMounts:
              - name: db
                mountPath: /var/lib/mysql2
        volumes: 
          - name: db
            persistentVolumeClaim:
              claimName: db-per-claim2
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: springboot
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None