apiVersion: apps/v1
kind: Deployment
metadata: 
    name: java
    namespace: springboot
    labels:
      app: java
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
        containers:
          - name: java
            image: ma5k/devops-demo:223
            imagePullPolicy: Always
            ports: 
             - containerPort: 8080
            env:
              - name: SPRING_DATASOURCE_PASSWORD
                value: ${SQL_PASSTWO_PSW}
              - name: SPRING_SECURITY_USER_PASSWORD
                value: ${HTML_PASS_PSW}
---
apiVersion: v1
kind: Service
metadata:
  name: java-servcie
  namespace: springboot
spec: 
  selector:
    app: java
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32520