version: '3.8'

services:
        db:
                image: mysql:8.0.31
                cap_add:
                      - SYS_NICE
                hostname: mysql
                restart: always
                environment:
                      - MYSQL_DATABASE=customerapi
                      - MYSQL_ROOT_PASSWORD=adminadmin
                ports:
                       - '3306:3306'
                volumes:
                      - db:/var/lib/mysql
                container_name: mysql
        java:
                ports:
                        - '8080:8080'
                build:  
                        context: ./
                        dockerfile: java-dockerfile
                links:
                        - "db:mysql"
                container_name: java
                restart: always
                depends_on:
                        - db
volumes:
        db:
                driver: local
